### ISSUE TITLE
Tree view can't be accessed in Sitecore Explorer (Visual Studio)

### ISSUE THREAD

**Issue by ryschwith** [sitecorerick/spark-sitecore-client#2]
Field works as expected in Content Editor, but when the item is accessed through Sitecore Rocks' Sitecore Explorer in Visual Studio it presents only a text field with a GUID rather than the tree view.

**Comment by sitecorerick** [comment]
Spark wasn't designed to support Sitecore Rocks. Also this library is deprecated and will not be upgraded to support Speak, Rocks, or Sitecore 8.1 Feel free to fork it if you want, but I recommend abandoning the Spark namespace for the https://github.com/search?q=user%3Asitecorerick+constellation Constellation namespace, which directly replaces it. - Note that I am now out of the custom Sitecore Client business, so custom fields will not be supported going forward.
